[package]
name = "gdp-router"
version = "0.1.0"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capsule = "0.1"
toml = "0.5.8"
