app_name = "gdp"
master_core = 0
duration = 50000
cores = [0]

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "eth1"
    device = "net_tap0"
    args = "iface=mytap"
    cores = [0]
    rxd = 1024
    txd = 1024


